name: Node Image Build & Deploy 
on: [push]
jobs:
  deploy-node:
    name: Deploy Node
    runs-on: ubuntu-latest
    steps:
    - 
      name: Checkout
      id: checkout
      uses: actions/checkout@v3

    - 
      name: Pre-build dev container image
      uses: devcontainers/ci@v0.2
      with:
        imageName: ghcr.io/jeremytondo/node
        cacheFrom: ghcr.io/jeremytondo/node
        push: always
